services:
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./chroma-data:/data  
    env_file:
      - ./.env


  flask:
    build: ./app  
    ports:
      - "5000:5000"  
    depends_on:
      - chroma
    env_file:
      - ./.env

volumes:
  chroma-data:
