services:
  flask:
    build: ./app  
    ports:
      - "5000:5000"  
    depends_on:
      - chroma
    environment:
      - CHROMA_DB_HOST=chroma
      - CHROMA_DB_PORT=8001
      - OPENAI_API_KEY=
 

  chroma:
    build: ./chromadb
    image: chromadb/chroma
    ports:
      - "8001:8001"
    volumes:
      - chroma-data:/data  
    environment:
      - OPENAI_API_KEY=

volumes:
  chroma-data:
