services:
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env


  flask:
    image: hrgpt.azurecr.io/flask:1.0
    ports:
      - "80:5000"
    depends_on:
      - chroma
    env_file:
      - ./.env

volumes:
  chroma-data: